"use client";

import { FormEvent, useEffect, useState } from "react";
import { AxiosError } from "axios";
import { membersApi, paymentsApi } from "@/lib/api";
import { Payment, PaymentMethod, PaymentStatus, User } from "@/types";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/components/language-provider";

export function PaymentRecorder() {
  const { t } = useLanguage();
  const [members, setMembers] = useState<User[]>([]); const [memberId, setMemberId] = useState(""); const [amount, setAmount] = useState(""); const [status, setStatus] = useState<PaymentStatus>("paid"); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>("cash"); const [payments, setPayments] = useState<Payment[]>([]); const [message, setMessage] = useState("");
  const current = new Date(); const month = `${current.getFullYear()}-${String(current.getMonth() + 1).padStart(2, "0")}`;
  useEffect(() => { void membersApi.getAll().then((response) => setMembers(response.data.data ?? [])).catch(() => setMessage("Unable to load members.")); }, []);
  const chooseMember = (id: string) => { setMemberId(id); const member = members.find((item) => item.id === Number(id)); if (member) setAmount(String(member.monthlyAmount)); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(""); try { const response = await paymentsApi.create({ userId: Number(memberId), amount: Number(amount), status, paymentMethod }); const payment = response.data.data; if (payment) setPayments((items) => [payment, ...items.filter((item) => item.id !== payment.id)]); setMessage("Payment recorded using the server date and month."); } catch (err) { const apiError = err as AxiosError<{ message?: string }>; setMessage(apiError.response?.data?.message ?? "Could not record payment."); } };
   return <section className="space-y-6"><form onSubmit={submit} className="surface grid gap-4 p-5 md:grid-cols-2"><label className="text-sm font-semibold">{t("member")}<select required value={memberId} onChange={(event) => chooseMember(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-input p-2"><option value="">{t("selectMember")}</option>{members.filter((member) => member.isActive).map((member) => <option key={member.id} value={member.id}>{member.name} — {member.phone}</option>)}</select></label><label className="text-sm font-semibold">{t("amount")}<input required min="0" type="number" value={amount} onChange={(event) => setAmount(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-input p-2" /></label><label className="text-sm font-semibold">{t("status")}<select value={status} onChange={(event) => setStatus(event.target.value as PaymentStatus)} className="mt-1 min-h-11 w-full rounded-xl border border-input p-2"><option value="paid">{t("paid")}</option><option value="partial">{t("partial")}</option><option value="unpaid">{t("unpaid")}</option></select></label><label className="text-sm font-semibold">{t("paymentMethod")}<select value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value as PaymentMethod)} className="mt-1 min-h-11 w-full rounded-xl border border-input p-2"><option value="cash">{t("cash")}</option><option value="bank_transfer">{t("bankTransfer")}</option><option value="jazzcash">{t("jazzcash")}</option><option value="easypaisa">{t("easypaisa")}</option><option value="other">{t("other")}</option></select></label><div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{t("serverMonth")}: <strong>{month}</strong><br />{t("exactTimestamp")}</div><Button type="submit" className="min-h-11 rounded-xl bg-emerald-700 hover:bg-emerald-800 md:col-span-2">{t("recordPayment")}</Button></form>{message && <p className="rounded-xl bg-muted p-3 text-sm">{message}</p>}<div><h2 className="mb-3 text-lg font-semibold">{t("paymentHistory")}</h2><div className="space-y-2">{payments.map((payment) => <div className="rounded-xl border p-3" key={payment.id}><div className="flex flex-wrap items-center justify-between gap-2"><span>{members.find((member) => member.id === payment.userId)?.name ?? `${t("member")} #${payment.userId}`} · Rs. {Number(payment.amount).toLocaleString()}</span><span>{payment.status} · {payment.month}</span></div><p className="mt-1 text-xs text-slate-500">{t("receipt")}: {payment.receiptNumber ?? "-"} · {payment.paidDate ? `${t("paidDate")}: ${new Date(payment.paidDate).toLocaleString()}` : `${t("recordedDate")}: ${new Date(payment.createdAt).toLocaleString()}`}</p></div>)}</div></div></section>;
}
