"use client";

import { useEffect, useMemo, useState } from "react";
import { membersApi } from "@/lib/api";
import { Payment, User } from "@/types";
import { useLanguage } from "@/components/language-provider";
import { PdfDownloadButton } from "@/components/pdf-download-button";

const monthLabels = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

export function PaymentGrid({ userId }: { userId: number }) {
  const { t } = useLanguage();
  const currentYear = new Date().getFullYear();
  const [year, setYear] = useState(currentYear); const [member, setMember] = useState<User | null>(null); const [payments, setPayments] = useState<Payment[]>([]); const [error, setError] = useState("");
  useEffect(() => { void membersApi.getById(userId).then((response) => { const data = response.data.data; setMember(data ?? null); setPayments(data?.payments ?? []); }).catch(() => setError("Unable to load your payment history.")); }, [userId]);
  const byMonth = useMemo(() => new Map(payments.filter((payment) => payment.year === year).map((payment) => [payment.month, payment])), [payments, year]);
   return <section className="space-y-5"><div className="rounded-lg border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><h2 className="text-xl font-semibold">{t("profile")}</h2>{member && <PdfDownloadButton title={`${member.name} - ${t("paymentHistory")}`} filename={`attock-welfare-${member.name.replace(/\s+/g, "-")}-${year}.pdf`} rows={[{ label: t("name"), value: member.name }, { label: t("fatherName"), value: member.fatherName || "-" }, { label: t("phone"), value: member.phone }, { label: t("monthlyAmount"), value: `Rs. ${Number(member.monthlyAmount).toLocaleString()}` }, ...Array.from({ length: 12 }, (_, index) => { const key = `${year}-${String(index + 1).padStart(2, "0")}`; const payment = payments.find((item) => item.month === key); return { label: monthLabels[index], value: payment ? `${payment.status} - ${payment.paidDate ? new Date(payment.paidDate).toLocaleDateString() : ""}` : t("unpaid") }; })]} />}</div>{member ? <dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">{t("name")}</dt><dd>{member.name}</dd></div><div><dt className="text-muted-foreground">{t("fatherName")}</dt><dd>{member.fatherName || "—"}</dd></div><div><dt className="text-muted-foreground">{t("phone")}</dt><dd>{member.phone}</dd></div><div><dt className="text-muted-foreground">{t("monthlyAmount")}</dt><dd>Rs. {Number(member.monthlyAmount).toLocaleString()}</dd></div></dl> : null}</div><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">{t("paymentHistory")}</h2><select value={year} onChange={(event) => setYear(Number(event.target.value))} className="rounded-md border border-input p-2">{[currentYear, currentYear - 1, currentYear - 2].map((value) => <option value={value} key={value}>{value}</option>)}</select></div>{error && <p className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{monthLabels.map((label, index) => { const month = `${year}-${String(index + 1).padStart(2, "0")}`; const payment = byMonth.get(month); const status = (payment?.status?.toLowerCase() ?? "unpaid") as "paid" | "unpaid" | "partial"; const accent = status === "paid" ? "border-green-400 bg-green-50" : status === "partial" ? "border-amber-400 bg-amber-50" : "border-red-200 bg-red-50"; return <article className="rounded-lg border p-4" key={month}><h3 className="font-semibold">{label}</h3><p className={`mt-2 ${accent} rounded px-2 py-1 capitalize`}>{status === "paid" ? `✓ ${t("paid")}` : status === "partial" ? `⚠ ${t("partial")}` : `✗ ${t("unpaid")}`}</p>{payment?.paidDate && <p className="mt-1 text-xs text-muted-foreground">{t("paid")} {new Date(payment.paidDate).toLocaleDateString()}</p>}</article>; })}</div></section>;
}
