"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { AxiosError } from "axios";
import { authApi } from "@/lib/api";
import { useAuthStore } from "@/lib/auth-store";
import { useLanguage } from "@/components/language-provider";
import { AuthLayout } from "@/components/auth-layout";

export default function LoginPage() { const router = useRouter(); const { setToken, setUser } = useAuthStore(); const { t } = useLanguage(); const [phone, setPhone] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const handleSubmit = async (event: FormEvent) => { event.preventDefault(); if (loading) return; setLoading(true); setError(""); try { const response = await authApi.login(phone.trim(), password); const { token, user } = response.data.data; localStorage.setItem("token", token); localStorage.setItem("user", JSON.stringify(user)); setToken(token); setUser(user); router.replace(user.role === "OWNER" ? "/owner" : user.role === "ADMIN" ? "/admin" : "/user"); } catch (err) { const apiError = err as AxiosError<{ message?: string }>; setError(apiError.response?.data?.message ?? "Login failed. Please check your credentials."); } finally { setLoading(false); } };
   return <AuthLayout eyebrow={t("welcomeBack")} title={t("welcomeBack")} description={t("loginSubtitle")}><div className="rounded-2xl border border-[#d9e7d8] bg-[#edf6ec] p-4"><p className="text-sm font-semibold text-[#245f4d]">One account, the right access</p><p className="mt-1 text-xs text-[#6c8178]">Your role automatically opens the correct workspace.</p></div>{error && <p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={handleSubmit} className="mt-7 space-y-5"><label className="block text-sm font-semibold text-[#53665d]">{t("phone")}<input required type="tel" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="03001234567" className="mt-2 min-h-12 w-full rounded-xl border border-[#d8ddd5] bg-white px-4 text-[#233d37]" /></label><label className="block text-sm font-semibold text-[#53665d]">{t("password")}<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder={t("password")} className="mt-2 min-h-12 w-full rounded-xl border border-[#d8ddd5] bg-white px-4 text-[#233d37]" /></label><button disabled={loading} className="min-h-12 w-full rounded-xl bg-[#245f4d] font-semibold text-white shadow-lg shadow-emerald-950/15 hover:bg-[#1c4e40] disabled:cursor-wait disabled:opacity-60">{loading ? t("loading") : t("login")}</button></form><div className="my-7 flex items-center gap-3 text-xs uppercase tracking-[0.2em] text-[#a0aaa2]"><span className="h-px flex-1 bg-[#dedfd7]" />{t("newMember")}<span className="h-px flex-1 bg-[#dedfd7]" /></div><Link className="flex min-h-12 items-center justify-center rounded-xl border border-[#c9ded0] bg-[#edf6ec] font-semibold text-[#245f4d] hover:bg-[#dfeee0]" href="/signup">{t("createUserAccount")}</Link></AuthLayout>; }
