"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { AxiosError } from "axios";
import { authApi } from "@/lib/api";
import { useAuthStore } from "@/lib/auth-store";
import { useLanguage } from "@/components/language-provider";
import { AuthLayout } from "@/components/auth-layout";

export default function SignupPage() { const router = useRouter(); const { setToken, setUser } = useAuthStore(); const { t } = useLanguage(); const [form, setForm] = useState({ name: "", fatherName: "", address: "", phone: "", email: "", password: "", confirmPassword: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); if (loading) return; setError(""); if (form.password !== form.confirmPassword) { setError(t("passwordMismatch")); return; } setLoading(true); try { const response = await authApi.register(form); const { token, user } = response.data.data; localStorage.setItem("token", token); localStorage.setItem("user", JSON.stringify(user)); setToken(token); setUser(user); router.replace("/user"); } catch (err) { const apiError = err as AxiosError<{ message?: string }>; setError(apiError.response?.data?.message ?? "Could not create your account."); } finally { setLoading(false); } };
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <AuthLayout eyebrow={t("newMember")} title={t("createAccount")} description={t("loginSubtitle")}><div className="mb-5 rounded-2xl border border-[#d9e7d8] bg-[#edf6ec] p-4 text-sm text-[#245f4d]">{t("createUserAccount")}</div>{error && <p className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label={t("name")} value={form.name} onChange={(value) => update("name", value)} required /><Field label={t("fatherName")} value={form.fatherName} onChange={(value) => update("fatherName", value)} /><Field className="sm:col-span-2" label={t("address")} value={form.address} onChange={(value) => update("address", value)} /><Field label={t("email")} value={form.email} onChange={(value) => update("email", value)} required type="email" /><Field label={t("phone")} value={form.phone} onChange={(value) => update("phone", value)} required type="tel" /><Field label={t("password")} value={form.password} onChange={(value) => update("password", value)} required type="password" minLength={8} /><Field label={t("confirmPassword")} value={form.confirmPassword} onChange={(value) => update("confirmPassword", value)} required type="password" minLength={8} /><button disabled={loading} className="min-h-12 rounded-xl bg-[#245f4d] font-semibold text-white shadow-lg shadow-emerald-950/15 hover:bg-[#1c4e40] disabled:opacity-60 sm:col-span-2">{loading ? t("loading") : t("createAccountButton")}</button></form><p className="mt-6 text-center text-sm text-[#718078]">{t("alreadyAccount")} <Link className="font-semibold text-[#245f4d] hover:underline" href="/login">{t("login")}</Link></p></AuthLayout>; }

function Field({ label, value, onChange, className = "", required = false, type = "text", minLength }: { label: string; value: string; onChange: (value: string) => void; className?: string; required?: boolean; type?: string; minLength?: number }) { return <label className={`block text-sm font-semibold text-[#53665d] ${className}`}>{label}<input required={required} minLength={minLength} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-[#d8ddd5] bg-white px-3 text-[#233d37]" /></label>; }
