export type Language = "en" | "ur";
export const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home", members: "Members", payments: "Payments", profile: "Profile", language: "اردو", dark: "Dark mode",
    owner: "Owner", admin: "Admin", member: "Member", controlCenter: "Control center", dailyOperations: "Daily operations", myContributions: "My contributions",
    login: "Login", signup: "Sign up", welcomeBack: "Welcome back", loginSubtitle: "Login to your secure contribution account.", createAccount: "Create your account", newMember: "New member", alreadyAccount: "Already have an account?", createUserAccount: "Create a user account",
    name: "Full name", email: "Email", fatherName: "Father name", address: "Address", phone: "Phone number", password: "Password", confirmPassword: "Confirm password", createAccountButton: "Create user account", loading: "Loading...",
    memberDirectory: "Member directory", searchMembers: "Search name, father, phone", addMember: "Add member", editMember: "Edit member", close: "Close", saveMember: "Save member", active: "Active", inactive: "Inactive", edit: "Edit", remove: "Remove", status: "Status", monthlyAmount: "Monthly amount", actions: "Actions",
    recordPayment: "Record payment", reports: "Reports", admins: "Admins", collected: "Collected", pending: "Pending", defaulters: "Defaulters", activeMembers: "Active members", whatsapp: "WhatsApp", paymentHistory: "Payment history", paid: "Paid", unpaid: "Unpaid", partial: "Partial", selectMember: "Select a member", amount: "Amount", serverMonth: "Server month/year", exactTimestamp: "Exact server timestamp is saved on submission.",
    createSuccess: "Account created successfully.", passwordMismatch: "Passwords do not match.", everyonePaid: "Everyone is paid for the current month.", actionNeeded: "Action needed", viewMembers: "View members", currentPeriod: "Live collection period", settings: "Settings", logout: "Logout", account: "Account", joinedDate: "Joined date", paidDate: "Paid date", recordedDate: "Recorded date", paymentMethod: "Payment method", cash: "Cash", bankTransfer: "Bank transfer", jazzcash: "JazzCash", easypaisa: "Easypaisa", other: "Other", receipt: "Receipt", totalExpected: "Total expected",
  },
  ur: {
    home: "صفحہ اول", members: "ارکان", payments: "ادائیگیاں", profile: "پروفائل", language: "English", dark: "ڈارک موڈ",
    owner: "مالک", admin: "منتظم", member: "رکن", controlCenter: "کنٹرول سینٹر", dailyOperations: "روزمرہ امور", myContributions: "میری ادائیگیاں",
    login: "لاگ اِن", signup: "رجسٹریشن", welcomeBack: "خوش آمدید", loginSubtitle: "اپنے محفوظ چندہ اکاؤنٹ میں لاگ اِن کریں۔", createAccount: "اپنا اکاؤنٹ بنائیں", newMember: "نیا رکن", alreadyAccount: "پہلے سے اکاؤنٹ موجود ہے؟", createUserAccount: "صارف اکاؤنٹ بنائیں",
    name: "پورا نام", email: "ای میل", fatherName: "والد کا نام", address: "پتہ", phone: "فون نمبر", password: "پاس ورڈ", confirmPassword: "پاس ورڈ کی تصدیق", createAccountButton: "صارف اکاؤنٹ بنائیں", loading: "لوڈ ہو رہا ہے...",
    memberDirectory: "ارکان کی فہرست", searchMembers: "نام، والد یا فون تلاش کریں", addMember: "رکن شامل کریں", editMember: "رکن میں ترمیم", close: "بند کریں", saveMember: "رکن محفوظ کریں", active: "فعال", inactive: "غیر فعال", edit: "ترمیم", remove: "ختم کریں", status: "حالت", monthlyAmount: "ماہانہ رقم", actions: "کارروائی",
    recordPayment: "ادائیگی درج کریں", reports: "رپورٹس", admins: "منتظمین", collected: "وصول شدہ", pending: "زیر التوا", defaulters: "نادہندگان", activeMembers: "فعال ارکان", whatsapp: "واٹس ایپ", paymentHistory: "ادائیگی کی تاریخ", paid: "ادا شدہ", unpaid: "غیر ادا شدہ", partial: "جزوی", selectMember: "رکن منتخب کریں", amount: "رقم", serverMonth: "سرور کا مہینہ/سال", exactTimestamp: "درست سرور وقت محفوظ کیا جائے گا۔",
    createSuccess: "اکاؤنٹ کامیابی سے بن گیا۔", passwordMismatch: "پاس ورڈ ایک جیسے نہیں ہیں۔", everyonePaid: "اس ماہ سب کی ادائیگی مکمل ہے۔", actionNeeded: "ضروری کارروائی", viewMembers: "ارکان دیکھیں", currentPeriod: "موجودہ وصولی کا دورانیہ", settings: "ترتیبات", logout: "لاگ آؤٹ", account: "اکاؤنٹ", joinedDate: "شمولیت کی تاریخ", paidDate: "ادائیگی کی تاریخ", recordedDate: "درج کرنے کی تاریخ", paymentMethod: "ادائیگی کا طریقہ", cash: "نقد", bankTransfer: "بینک ٹرانسفر", jazzcash: "جاز کیش", easypaisa: "ایزی پیسہ", other: "دیگر", receipt: "رسید", totalExpected: "کل متوقع رقم",
  },
};
